### ISSUE TITLE
Can you make another one but for those of us who use native Kali Linux?

### ISSUE THREAD

**Issue by Juanchith** [ZLCube/KaliBspwm#7]
What happens is I installed it on my native Kali Linux and it has many bugs. It can't connect to Wi-Fi, it doesn't identify IPs, and it doesn't show the modules that are supposed to be in .config, among other things. Please help.

**Comment by ZLCube** [comment]
This script is also supported by native kali, for the IP module you need to change the network interface under ~/.config/bin/ethernet_status since in vm the host ip address is under eth0 or tun0 while in a native OS is usually under ens33 or even wlan0, this will depend on your asset and ou can check that using the ifconfig command. For target and VPN you can find them under the same directory ~/.config/bin/htb* and for the polybar resize of the modules along with the rest of the configurrations you can find them under ~/.config/polybar/ in which workspace.ini is the workspace center bar, current.ini are the rest of the modules and colors.ini are the color pallets. Hope this is useful and help you solve the issues.

**Comment by Juanchith** [comment]
Thanks, I fixed it. Now, to make it so that I can see and select the Wi-Fi points where I can connect, since when I press the icon it doesn't show me any Wi-Fi connections to connect to. Another thing is that the battery doesn't show up.

**Comment by Juanchith** [comment]
Thanks, I fixed it. Now, to make it so that I can see and select the Wi-Fi points where I can connect, since when I press the icon it doesn't show me any Wi-Fi connections to connect to. Another thing is that the battery doesn't show up.
